apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
namespace: swim-dev

bases:
- ../base

resources:
- ./namespace.yaml

images:
- name: "353593603949.dkr.ecr.us-west-2.amazonaws.com/swim"
  # don't change by hand unless you're rolling back.  Let ada.devops manage the tags when the container is built
  newTag: 0.0.2
