apiVersion: v1
kind: Service
metadata:
  name: swim
  labels:
    app: "swim"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"

spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: "swim"
  type: LoadBalancer
  #type: NodePort
