apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swim
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: swim
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: argocd/workloads/swim/prod
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
