---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: mongodb
  namespace: namespace_name
  labels:
    app: app_name
    owner: owner_name
    environment: environment_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_name
      owner: owner_name
      environment: environment_name
  template:
    metadata:
      labels:
        app: app_name
        owner: owner_name
        environment: environment_name
    spec:
      containers:
      - name: "mongodb"
        image: mongo:5.0.3-focal
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
