apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
namespace: mongodb

resources:
- ./namespace.yaml
- ./deployment.yaml
- ./service.yaml

commonLabels:
  app: mongodb
  owner: devops
  environment: database
